// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Optsol.GestaoEstoque.Infra.Data;

namespace Optsol.GestaoEstoque.Infra.Migrations
{
    [DbContext(typeof(GestaoEstoqueContext))]
    partial class GestaoEstoqueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Optsol.GestaoEstoque.Dominio.Entidades.Deposito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LOCALIZACAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("DEPOSITO");
                });

            modelBuilder.Entity("Optsol.GestaoEstoque.Dominio.Entidades.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DepositoId")
                        .HasColumnType("int")
                        .HasColumnName("DEPOSITOID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOME");

                    b.Property<int>("Preco")
                        .HasColumnType("int")
                        .HasColumnName("PRECO");

                    b.HasKey("Id");

                    b.HasIndex("DepositoId");

                    b.ToTable("PRODUTO");
                });

            modelBuilder.Entity("Optsol.GestaoEstoque.Dominio.Entidades.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comprador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("COMPRADOR");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA");

                    b.HasKey("Id");

                    b.ToTable("VENDA");
                });

            modelBuilder.Entity("Optsol.GestaoEstoque.Dominio.Entidades.VendaProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("PRODUTOID");

                    b.Property<int>("QuantidadeVendida")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADEVENDIDA");

                    b.Property<int>("VendaId")
                        .HasColumnType("int")
                        .HasColumnName("VENDAID");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("VENDAPRODUTO");
                });

            modelBuilder.Entity("Optsol.GestaoEstoque.Dominio.Entidades.Produto", b =>
                {
                    b.HasOne("Optsol.GestaoEstoque.Dominio.Entidades.Deposito", "Deposito")
                        .WithMany("Produtos")
                        .HasForeignKey("DepositoId");

                    b.Navigation("Deposito");
                });

            modelBuilder.Entity("Optsol.GestaoEstoque.Dominio.Entidades.VendaProduto", b =>
                {
                    b.HasOne("Optsol.GestaoEstoque.Dominio.Entidades.Produto", "Produto")
                        .WithMany("Vendas")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Optsol.GestaoEstoque.Dominio.Entidades.Venda", "Venda")
                        .WithMany("Produtos")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Optsol.GestaoEstoque.Dominio.Entidades.Deposito", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Optsol.GestaoEstoque.Dominio.Entidades.Produto", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("Optsol.GestaoEstoque.Dominio.Entidades.Venda", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
